services:
  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: rapidprd-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: rapidprd-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
